// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOeo-VtXjuPfhOw4_GT-zlNWbPPQy_pAE',
    appId: '1:431719920653:web:7d5bf03a1f0d5bfd9a5144',
    messagingSenderId: '431719920653',
    projectId: 'fitnesstracker-66a25',
    authDomain: 'fitnesstracker-66a25.firebaseapp.com',
    storageBucket: 'fitnesstracker-66a25.firebasestorage.app',
    measurementId: 'G-FJ8YH5VCV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdPrWil1tIOrUWmziG8Hpl5sS_BGcaotU',
    appId: '1:431719920653:android:f2721d154712504f9a5144',
    messagingSenderId: '431719920653',
    projectId: 'fitnesstracker-66a25',
    storageBucket: 'fitnesstracker-66a25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClrXvDVi4lI8iilNYVzk0PzO6k9cxo2gQ',
    appId: '1:431719920653:ios:7c0f81aa9f63bfe29a5144',
    messagingSenderId: '431719920653',
    projectId: 'fitnesstracker-66a25',
    storageBucket: 'fitnesstracker-66a25.firebasestorage.app',
    iosBundleId: 'com.example.rockiesFitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClrXvDVi4lI8iilNYVzk0PzO6k9cxo2gQ',
    appId: '1:431719920653:ios:7c0f81aa9f63bfe29a5144',
    messagingSenderId: '431719920653',
    projectId: 'fitnesstracker-66a25',
    storageBucket: 'fitnesstracker-66a25.firebasestorage.app',
    iosBundleId: 'com.example.rockiesFitnessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOeo-VtXjuPfhOw4_GT-zlNWbPPQy_pAE',
    appId: '1:431719920653:web:2777a2fe46e6697d9a5144',
    messagingSenderId: '431719920653',
    projectId: 'fitnesstracker-66a25',
    authDomain: 'fitnesstracker-66a25.firebaseapp.com',
    storageBucket: 'fitnesstracker-66a25.firebasestorage.app',
    measurementId: 'G-88SLXC4GVR',
  );
}
